### ISSUE TITLE
Any thoughts on turbolinks without using elm?

### ISSUE THREAD

**Issue by dhirajbajaj** [miguelcoba/olmeca#1]
Thanks for providing this quick starter template. Its really helpful to quickly learn. 👍 

Pardon this question, I am new to phoenix and thinking of not using the elm part as its another language to learn. 

- Instead, what do you suggest about using turbolinks with server side views already present?
- Does elm make it very fast? Can you share your views about it?

**Comment by miguelcoba** [comment]
Hi, I have no experience at all with turbolinks so I can't give an informed opinion about that. I used this as my starting point for side-projects with Elixir and Elm. Maybe you can find some project with phoenix + turbolinks, but most likely, the Rails stack is a better way to use it.

Why Elm? I think is a very powerful language within its own constraints. Those constraints (functional programming) are by themselves very mind opening and I like that. About speed, I don't really care as my projects are not really the ones where the user notices any difference in response times. Developing with it, on the other side, it is really delightful and the Elm architecture is very easy to think about when developing webapps.

Cheers
